### ISSUE TITLE
ARC Issue

### ISSUE THREAD

**Issue by radven** [amarcadet/XMLReader#1]
XCode generates a "Pointer to non-const type" error on this line now:
  NSError **errorPointer;

I'm not sure of the best workaround.

**Comment by bayfatih2000** [comment]
How can I use XMLReader with ARC? I converted code with Xcode but it does not work. Please help !!!

**Comment by amarcadet** [comment]
Hi,

My component doesn't support ARC for now but there's a fork that support it here : https://github.com/snip3r8/XMLReader

Let me know if it's ok for you.

Antoine

**Comment by bayfatih2000** [comment]
It is compiled successfully but it causes runtime error (EXC_BAD_ACCESS). Do you have any idea?

**Comment by amarcadet** [comment]
No idea without code to read.

It could come from somewhere else in your program, furthermore I'm not the author of the fork, maybe you should ask snip3r8.

Antoine

**Comment by amarcadet** [comment]
Just merged pull request from snip3r8 that add ARC support
