### ISSUE TITLE
Cocoapods Support

### ISSUE THREAD

**Issue by RyanCopley** [amarcadet/XMLReader#10]
Would you mind adding this to cocoapods? If you don't I'm going to end up forking and doing it myself

**Comment by amarcadet** [comment]
Hello first.

Looks like you already [forked my code](https://github.com/RyanCopley/XMLReader).
2 hours delay for an answer, sorry but I can't afford that.

If you had done some search before opening this issue you would have noticed that someone had already published `XMLReader` to [cocoapods](https://github.com/CocoaPods/Specs/blob/master/XMLReader/0.0.2/XMLReader.podspec).

Looking at the [source code](https://github.com/blakewatters/XML-to-NSDictionary/blob/master/XMLReader.h#L5) you will notice that this is exactly the same code.

It's not that I didn't want to publish my code for celebrity, money and glory, but cocoapods didn't exists at the time I developed it.

Nevertheless, I'm happy that you've found my library useful and wish you best luck with the open source community.

**Comment by RyanCopley** [comment]
You seem to have taken this a bit too personally. Also, if you actually look at the source code, you will realize that the XMLReader in CocoaPods that someone else sent is actually not the same. I didn't do this to steal your glory, I did it because Cocoapods is one of the most convenient way to handle dependencies and it wasn't in the Spec repo. If you want to adjust the Cocoapod spec to point it to your repository, go ahead.
