### ISSUE TITLE
XMLReader don't give data in correct format if there is only 1 object

### ISSUE THREAD

**Issue by fparkar** [amarcadet/XMLReader#11]
Please take a look at question i have here.

http://stackoverflow.com/questions/22577136/xmlreader-not-working-when-have-only-1-data

Basically, when I have one object, the format that you have is incorrect. For more info please visit stackoverflow link provided above.

**Comment by amarcadet** [comment]
The [answer](http://stackoverflow.com/a/22577814/3350749) provided my Jody Hagins is the correct solution.

In fact when iterating through the XML there is no way to know if it's an object (`NSDictionary`) or a list (`NSArray`) until a second occurence of the same key has been discovered.

Please report to the [readme](https://github.com/amarcadet/XMLReader#sometimes-i-get-an-nsdictionary-while-i-must-get-an-nsarray-why-) which provides a sample code to solve that "problem".

Sorry about that design flaw but there is no way for the library to know if your XML contain array or object. It's up to the developer to know the data he is manipulating.
