### ISSUE TITLE
Add support for SOAP tags

### ISSUE THREAD

**Issue by idanmos** [amarcadet/XMLReader#7]
How can I edit and add custom tags to support SOAP?

**Comment by amarcadet** [comment]
Sorry for the delay but supporting SOAP is not the purpose of this library.

I use it to work with SOAP XML, so you shouldn't have any problem to do that.

Look at [these options](https://github.com/amarcadet/XMLReader/blob/master/XMLReader.h#L12-L14) and especially `XMLReaderOptionsProcessNamespaces`.
